# Generated by Django 2.2.16 on 2021-10-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_auto_20211010_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
