# Generated by Django 2.2.16 on 2021-10-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_auto_20211012_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[('admin', 'admin'), ('moderator', 'moderator'), ('user', 'user')], default='user'),
        ),
    ]
