# Generated by Django 2.2.16 on 2021-10-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_auto_20211012_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
    ]
